Repository DGtal-team/DGtalTools, pull requests merged in 2019-10, with the labels that each got.

#356 Fix boost prog option link
  CMakeLists.txt
  ChangeLog.md
Labels: Compilation issues, Ready For Reviews

#355 Passing argument by const reference in volSubSample.
  volumetric/volSubSample.cpp
Labels: Ready For Reviews, Volumetric, bug

#360 Fixing doxygen source url by downloading it from SourceForge
  .travis/install_doxygen.sh
  ChangeLog.md
Labels: Compilation issues, Ready For Reviews

#359 Passing argument by const reference in volSubSample.
  ChangeLog.md
  volumetric/volSubSample.cpp
Labels: Ready For Reviews
